# Generated by Django 5.2.6 on 2025-10-23 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(help_text='Modelo del vehículo (Ej: Ford Mustang)', max_length=100)),
                ('año', models.IntegerField()),
                ('color', models.CharField(max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cant_disponible', models.IntegerField(default=0)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='vehiculos/')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
            },
        ),
        migrations.CreateModel(
            name='ServicioMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cliente', models.CharField(help_text='Identificador del cliente', max_length=50)),
                ('tipo_servicio', models.CharField(max_length=100)),
                ('fecha_servicio', models.DateField()),
                ('costo_servicio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('proveedor', models.CharField(max_length=100)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='app_vehiculosYservicios.vehiculo')),
            ],
            options={
                'verbose_name': 'Servicio de Mantenimiento',
                'verbose_name_plural': 'Servicios de Mantenimiento',
            },
        ),
    ]
